use_frameworks!

source 'https://cdn.cocoapods.org/'
source 'https://github.com/Kalanhall/Specs.git'

platform :ios, '9.0'

target 'KLConsole_Example' do
  pod 'KLConsole', :path => '../'
  pod 'YKWoodpecker'

  target 'KLConsole_Tests' do
    inherit! :search_paths

    
  end
end
